#!/command/with-contenv sh

if [ "$SCHEDULE_ENABLED" = "true" ]; then
    echo "Schedule is enabled"
    artisan schedule:work --whisper
else
    echo "Schedule is disabled"
    s6-svc -Od .
    exit 0
fi
