#!/command/with-contenv sh

if [ "$QUEUE_ENABLED" = "true" ]; then
    echo "✅ Queue is enabled"
    php "$APP_BASE_DIR/artisan" queue:work \
        --max-jobs $QUEUE_MAX_JOBS \
        --sleep $QUEUE_SLEEP \
        --rest $QUEUE_REST \
        --timeout $QUEUE_TIMEOUT \
        --tries $QUEUE_TRIES \
        --force
else
    echo "❌ Queue is disabled"
    s6-svc -Od .
    exit 0
fi
